# Generated by Django 4.1.2 on 2022-10-11 16:06
# Essa migração faz a CRIAÇÃO da tabela no banco de dados baseado no modelo de tabela professor que eu criei
# So usar o comando python .\manage.py makemigrations que ele cria sozinho baseado nos models que existem
# .\manage.py migrate executa os arquivos de migração criando a tabela no banco
# Se eu quiser ver o banco é so clicar no arquivo db.sqlite3 ali em baixo, é um banco de dados 'offline'

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descricao', models.TextField()),
                ('foto', models.URLField(max_length=255)),
            ],
        ),
    ]
